// <auto-generated/>

//#region Countdown
declare namespace HordeResurrection.Basic.Debugger.Countdowns {
	class /* struct */ Countdown extends System.ValueType {

		// Constructors:
		constructor(
			leftTicks: number
		);

		// Fields:
		static readonly Zero: HordeResurrection.Basic.Debugger.Countdowns.Countdown;
		static readonly Infinite: HordeResurrection.Basic.Debugger.Countdowns.Countdown;
		static readonly /* const */ InfiniteValue: number; // = 2147483647

		// Properties:
		LeftTicks: number;
		readonly IsExpired: boolean;

		// Methods:
		Tick(): HordeResurrection.Basic.Debugger.Countdowns.Countdown;

		GetLeftTicksString(): string;

		// Default parameterless constructor for value types
		constructor();
	}
}
//#endregion

//#region ResettableCountdown
declare namespace HordeResurrection.Basic.Debugger.Countdowns {
	class ResettableCountdown extends System.Object {

		// Constructors:
		constructor(
			expirationTicks: number
		);

		constructor(
			expirationTicks: number,
			initialValue: number
		);

		// Fields:
		static readonly /* const */ InfiniteTicks: number; // = 2147483647

		// Properties:
		readonly ExpirationTicks: number;
		readonly LeftTicks: number;
		readonly IsExpired: boolean;
		readonly PastTicks: number;

		// Methods:
		Tick(): boolean;

		Reset(): void;

		Reinit(
			expirationTicks: number
		): void;

		static CreateInfiniteCountdown(): HordeResurrection.Basic.Debugger.Countdowns.ResettableCountdown;
	}
}
//#endregion

//#region Types shorthand
// ----------------------------------------------------- //
// ---------========= Types shorthand =========--------- //
// ----------------------------------------------------- //
/*
export const Countdown = HordeResurrection.Basic.Debugger.Countdowns.Countdown;
export type Countdown = HordeResurrection.Basic.Debugger.Countdowns.Countdown;
export const ResettableCountdown = HordeResurrection.Basic.Debugger.Countdowns.ResettableCountdown;
export type ResettableCountdown = HordeResurrection.Basic.Debugger.Countdowns.ResettableCountdown;
*/
//#endregion
